translations:
  - name: nasb
    fullName: NASB
    description: New American Standard Bible
    ftp:
      host: ftp.crosswire.org
      port: 21
      user: anonymous
      password: password
      directory: /pub/sword/lockmanraw/modules/texts/ztext/nasb
    
  - name: leb
    fullName: LEB
    description: Lexham English Bible
    ftp:
      host: ftp.crosswire.org
      port: 21
      user: anonymous
      password: password
      directory: /pub/sword/raw/modules/texts/ztext/leb

  - name: kjv
    fullName: KJV
    description: King James Version
    ftp:
      host: ftp.crosswire.org
      port: 21
      user: anonymous
      password: password
      directory: /pub/sword/raw/modules/texts/ztext/kjv

  - name: mkjv
    fullName: MKJV
    description: Modern King James Version
    ftp:
      host: ftp.crosswire.org
      port: 21
      user: anonymous
      password: password
      directory: /pub/sword/raw/modules/texts/ztext/mkjv

  - name: bsb
    fullName: BSB
    description: Berean Study Bible
    ftp:
      host: ftp.crosswire.org
      port: 21
      user: anonymous
      password: password
      directory: /pub/sword/raw/modules/texts/ztext/bsb

  - name: emtv
    fullName: EMTV
    description: English Majority Text Version
    testaments: nt
    ftp:
      host: ftp.crosswire.org
      port: 21
      user: anonymous
      password: password
      directory: /pub/sword/raw/modules/texts/ztext/emtv

  - name: akjv
    fullName: AKJV
    description: American King James Version
    ftp:
      host: ftp.crosswire.org
      port: 21
      user: anonymous
      password: password
      directory: /pub/sword/raw/modules/texts/ztext/akjv
