apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: bible-soh-re
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie
  bootstrap:
    initdb:
      database: bible
      owner: bible
  storage:
    size: 5Gi
    storageClass: longhorn-single-replica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bible-translations
  namespace: bible-soh-re
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bible-uploads
  namespace: bible-soh-re
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
