name: Call Reusable Golang CI Workflow

on:
  push:

permissions:
  contents: read
  security-events: write

jobs:
  golang-ci:
    uses: Jmainguy/golang-workflows/.github/workflows/golang-ci.yml@v2.1.1
    with:
      docker: true
